#pragma once

#define BRYN_MOUSE_BUTTON_1         0
#define BRYN_MOUSE_BUTTON_2         1
#define BRYN_MOUSE_BUTTON_3         2
#define BRYN_MOUSE_BUTTON_4         3
#define BRYN_MOUSE_BUTTON_5         4
#define BRYN_MOUSE_BUTTON_6         5
#define BRYN_MOUSE_BUTTON_7         6
#define BRYN_MOUSE_BUTTON_8         7
#define BRYN_MOUSE_BUTTON_LAST      BRYN_MOUSE_BUTTON_8
#define BRYN_MOUSE_BUTTON_LEFT      BRYN_MOUSE_BUTTON_1
#define BRYN_MOUSE_BUTTON_RIGHT     BRYN_MOUSE_BUTTON_2
#define BRYN_MOUSE_BUTTON_MIDDLE    BRYN_MOUSE_BUTTON_3